### ISSUE TITLE
having multiple descriptors with different transaction value fails

### ISSUE THREAD

**Issue by hechmi-dammak-xenit** [dgradecak/alfresco-mvc#26]
having different values for the transaction for multiple  web script descriptors result in an error when calling endpoints that requires read and write transaction with an exception :
`ERROR [extensions.webscripts.AbstractRuntime] [http-nio-8080-exec-11] Exception from executeScript: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.alfresco.service.transaction.ReadOnlyServerException: 03260118 Access Denied.  The system is currently in read-only mode.
java.io.IOException: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.alfresco.service.transaction.ReadOnlyServerException: 03260118 Access Denied.  The system is currently in read-only mode.
        at com.gradecak.alfresco.mvc.webscript.DispatcherWebscript.execute(DispatcherWebscript.java:125)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:506)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:685)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:721)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:413)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:309)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:423)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
        at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:131)
        at org.alfresco.repo.web.scripts.AlfrescoWebScriptServlet.service(AlfrescoWebScriptServlet.java:43)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.extensions.webscripts.servlet.SecurityHeadersFilter.doFilter(SecurityHeadersFilter.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.alfresco.web.app.servlet.ServletMetricsFilter.doFilter(ServletMetricsFilter.java:161)
        at org.alfresco.repo.web.filter.beans.BeanProxyFilter.doFilter(BeanProxyFilter.java:89)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.alfresco.web.app.servlet.ClearSecurityContextFilter.doFilter(ClearSecurityContextFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.alfresco.service.transaction.ReadOnlyServerException: 03260118 Access Denied.  The system is currently in read-only mode.
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
        at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:920)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:684)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at com.gradecak.alfresco.mvc.webscript.DispatcherWebscript.execute(DispatcherWebscript.java:121)
        ... 41 more
Caused by: org.alfresco.service.transaction.ReadOnlyServerException: 03260118 Access Denied.  The system is currently in read-only mode.
        at org.alfresco.repo.domain.node.AbstractNodeDAOImpl.getCurrentTransaction(AbstractNodeDAOImpl.java:586)
        at org.alfresco.repo.domain.node.AbstractNodeDAOImpl.newNodeImpl(AbstractNodeDAOImpl.java:1309)
        at org.alfresco.repo.domain.node.AbstractNodeDAOImpl.newNode(AbstractNodeDAOImpl.java:1233)
        at org.alfresco.repo.node.db.DbNodeServiceImpl.createNode_aroundBody24(DbNodeServiceImpl.java:392)
        at org.alfresco.repo.node.db.DbNodeServiceImpl$AjcClosure25.run(DbNodeServiceImpl.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:179)
        at org.alfresco.traitextender.RouteExtensions.intercept(RouteExtensions.java:100)
        at org.alfresco.repo.node.db.DbNodeServiceImpl.createNode(DbNodeServiceImpl.java:342)
        at jdk.internal.reflect.GeneratedMethodAccessor197.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.alfresco.repo.lock.mem.LockableAspectInterceptor.invoke(LockableAspectInterceptor.java:244)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy39.createNode(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor197.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.alfresco.repo.tenant.MultiTNodeServiceInterceptor.invoke(MultiTNodeServiceInterceptor.java:111)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy39.createNode(Unknown Source)
        at org.alfresco.repo.version.Version2ServiceImpl.createVersionHistory(Version2ServiceImpl.java:395)
        at org.alfresco.repo.version.Version2ServiceImpl.createVersion(Version2ServiceImpl.java:263)
        at org.alfresco.repo.version.Version2ServiceImpl.createVersion_aroundBody2(Version2ServiceImpl.java:158)
        at org.alfresco.repo.version.Version2ServiceImpl$AjcClosure3.run(Version2ServiceImpl.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:179)
        at org.alfresco.traitextender.RouteExtensions.intercept(RouteExtensions.java:100)
        at org.alfresco.repo.version.Version2ServiceImpl.createVersion(Version2ServiceImpl.java:142)
        at org.alfresco.repo.version.VersionServiceImpl.ensureVersioningEnabled_aroundBody4(VersionServiceImpl.java:1011)
        at org.alfresco.repo.version.VersionServiceImpl$AjcClosure5.run(VersionServiceImpl.java:1)
		 at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:179)
        at org.alfresco.traitextender.RouteExtensions.intercept(RouteExtensions.java:100)
        at org.alfresco.repo.version.VersionServiceImpl.ensureVersioningEnabled(VersionServiceImpl.java:967)
`

**Comment by dgradecak** [comment]
this is an old conseptual decision and somewhat a small mistake in Alfresco-MVC. A single webscript for a randomly defined HTTP webscript descriptor was created and the rest of the webscript beans were registered as aliases. That is the "mistake" where in the listing of webscripts only one webscript is seen and the rest was not seen. This also makes the transactions or runas (anything in the webscript xml descriptor) problematic, since the definition would actually always be from the first defined bean.

This will be fixed on the dev branch for now.

I did not test it with records management or custom context refreshes.

**Comment by dgradecak** [comment]
I will also add some extra HTTP methods => HEAD, OPTIONS, PATCH and TRACE as default configuration

        alfresco-mvc-rest/src/main/resources/alfresco/extension/templates/webscripts/alfresco-mvc/mvc.head.desc.xml
        alfresco-mvc-rest/src/main/resources/alfresco/extension/templates/webscripts/alfresco-mvc/mvc.options.desc.xml
        alfresco-mvc-rest/src/main/resources/alfresco/extension/templates/webscripts/alfresco-mvc/mvc.patch.desc.xml
        alfresco-mvc-rest/src/main/resources/alfresco/extension/templates/webscripts/alfresco-mvc/mvc.trace.desc.xml

so from now it will be possible to configure each descriptor differently. 

The default alfresco-mvc.mvc descrriptors will be adapted and this might be problematic for people starting a RW TX inside a http GET method and such things. However, this would indicate a malformed rest api and is subject to change or to be wrapped in itsown transaction separatly (better not to use nested transactions).
